name: pokedex
description: "PokedexApp"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.7
  http: ^1.2.1
  provider: ^6.1.1
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  ios: true
  image_path: "assets/images/Pokeball.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/type_short_icons/
    - assets/images/type_long_icons/
    - assets/raw/
